import os

MAX_X = 800
MAX_Y = 600
FRAME_RATE = 30

DEFAULT_SQUARE_SIZE = 20
DEFAULT_FONT_SIZE = 20
DEFAULT_TEXT_OFFSET = 4



SOUND_START = os.path.join(os.getcwd(), "./asteroids/assets/start.wav")
SOUND_HIT = os.path.join(os.getcwd(), "./asteroids/assets/explosion.wav")
SOUND_OVER = os.path.join(os.getcwd(), "./asteroids/assets/over.wav")

BALL_X = MAX_X / 2
BALL_Y = MAX_Y - 125

ASTEROID_DX = 0
ASTEROID_DY = 1
L2ASTEROID_DY = 1.25
L3ASTEROID_DY = 1.5
L4ASTEROID_DY = 1.75
L5ASTEROID_DY = 2
L6ASTEROID_DY = 2.25

PADDLE_X = MAX_X / 2
PADDLE_Y = MAX_Y - 35

SHIP_WIDTH = 48
SHIP_HEIGHT = 24

BRICK_SPACE = 5

SHIP_SPEED = 12
L2SHIP_SPEED = 15

PADDLE_WIDTH = 96
PADDLE_HEIGHT = 24

ASTEROID_WIDTH = 64
ASTEROID_HEIGHT = 64

PROJECTILE_WIDTH = 15
PROJECTILE_HEIGHT = 15

PROJECTILE_DY = -9
PROJECTILE_DX = 0

L2PROJECTILE_DY = -12
L3PROJECTILE_DY = -15

